version: '3'

services:
  web:
    container_name: web
    build: .
    restart: unless-stopped
    environment:
      - PUBLIC_POCKETBASE_URL=${PUBLIC_POCKETBASE_URL}
      - PORT=3013
    ports:
      - '3013:3013'
    networks:
      - caddy-net

  pocketbase:
    container_name: pocketbase
    build: ./pocketbase-docker
    restart: unless-stopped
    environment:
      - PORT=8013
    ports:
      - '8013:8013'
    networks:
      - caddy-net

  caddy:
    container_name: caddy
    build: ./caddy-with-cloudflare
    networks:
      - web
      - caddy-net
    restart: unless-stopped
    environment:
      - PUBLIC_POCKETBASE_URL=${PUBLIC_POCKETBASE_URL}
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL}
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp' # QUIC protocol support: https://www.chromium.org/quic/
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

networks:
  web:
    external: true
  caddy-net:
    external: false
    driver: bridge

volumes:
  caddy_data:
    external: true
  caddy_config:
