version: '3'

services:
  web:
    container_name: web
    image: 'ghcr.io/plushugh/scoring/web:main'
    restart: unless-stopped
    environment:
      - PORT=3013
    volumes:
      - $PWD/.env:/app/.env
    ports:
      - '3013:3013'
    networks:
      - caddy-net

  pocketbase:
    container_name: pocketbase
    image: 'ghcr.io/plushugh/scoring/pocketbase:main'
    restart: unless-stopped
    environment:
      - PORT=8013
    volumes:
      - $PWD/pocketbase/pb_data:/pb_data
    ports:
      - '8013:8013'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8013/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - caddy-net

  caddy:
    container_name: caddy
    image: 'ghcr.io/plushugh/scoring/caddy:main'
    networks:
      - web
      - caddy-net
    restart: unless-stopped
    environment:
      - PUBLIC_POCKETBASE_URL=${PUBLIC_POCKETBASE_URL}
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL}
      - CADDY_DNS_APIKEY=${CADDY_DNS_APIKEY}
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp' # QUIC protocol support: https://www.chromium.org/quic/
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

networks:
  web:
    external: true
  caddy-net:
    external: false
    driver: bridge

volumes:
  caddy_data:
    external: true
  caddy_config:
